local Percussion = Musician.MIDI_PERCUSSIONS
local Instrument = Musician.MIDI_INSTRUMENTS

Musician.MIDI_INSTRUMENT_MAPPING = {
	-- Piano
	[Instrument.AcousticGrandPiano] = "dulcimer",
	[Instrument.BrightAcousticPiano] = "dulcimer",
	[Instrument.ElectricGrandPiano] = "dulcimer",
	[Instrument.HonkyTonkPiano] = "dulcimer",
	[Instrument.ElectricPiano1] = "dulcimer",
	[Instrument.ElectricPiano2] = "dulcimer",
	[Instrument.Harpsichord] = "harp",
	[Instrument.Clavi] = "harp",

	-- Chromatic Percussion
	[Instrument.Celesta] = "dulcimer",
	[Instrument.Glockenspiel] = "dulcimer",
	[Instrument.MusicBox] = "harp",
	[Instrument.Vibraphone] = "dulcimer",
	[Instrument.Marimba] = "dulcimer",
	[Instrument.Xylophone] = "dulcimer",
	[Instrument.TubularBells] = "dulcimer",
	[Instrument.Dulcimer] = "dulcimer",

	-- Organ
	[Instrument.DrawbarOrgan] = "accordion",
	[Instrument.PercussiveOrgan] = "accordion",
	[Instrument.RockOrgan] = "accordion",
	[Instrument.ChurchOrgan] = "accordion",
	[Instrument.ReedOrgan] = "accordion",
	[Instrument.Accordion] = "accordion",
	[Instrument.Harmonica] = "accordion",
	[Instrument.TangoAccordion] = "accordion",

	-- Guitar
	[Instrument.AcousticGuitarNylon] = "lute",
	[Instrument.AcousticGuitarSteel] = "lute",
	[Instrument.ElectricGuitarJazz] = "clean-guitar",
	[Instrument.ElectricGuitarClean] = "clean-guitar",
	[Instrument.ElectricGuitarMuted] = "clean-guitar",
	[Instrument.OverdrivenGuitar] = "distorsion-guitar",
	[Instrument.DistortionGuitar] = "distorsion-guitar",
	[Instrument.Guitarharmonics] = "distorsion-guitar",

	-- Bass
	[Instrument.AcousticBass] = "lute",
	[Instrument.ElectricBassFinger] = "bass-guitar",
	[Instrument.ElectricBassPick] = "bass-guitar",
	[Instrument.FretlessBass] = "bass-guitar",
	[Instrument.SlapBass1] = "bass-guitar",
	[Instrument.SlapBass2] = "bass-guitar",
	[Instrument.SynthBass1] = "bass-guitar",
	[Instrument.SynthBass2] = "bass-guitar",

	-- Strings
	[Instrument.Violin] = "fiddle",
	[Instrument.Viola] = "fiddle",
	[Instrument.Cello] = "viola-da-gamba",
	[Instrument.Contrabass] = "viola-da-gamba",
	[Instrument.TremoloStrings] = "fiddle",
	[Instrument.PizzicatoStrings] = "lute",
	[Instrument.OrchestralHarp] = "harp",
	[Instrument.Timpani] = "none",

	-- Ensemble
	[Instrument.StringEnsemble1] = "fiddle",
	[Instrument.StringEnsemble2] = "fiddle",
	[Instrument.SynthStrings1] = "fiddle",
	[Instrument.SynthStrings2] = "fiddle",
	[Instrument.ChoirAahs] = "male-voice",
	[Instrument.VoiceOohs] = "female-voice",
	[Instrument.SynthVoice] = "female-voice",
	[Instrument.OrchestraHit] = "lute",

	-- Brass
	[Instrument.Trumpet] = "trumpet",
	[Instrument.Trombone] = "sackbut",
	[Instrument.Tuba] = "war-horn",
	[Instrument.MutedTrumpet] = "trumpet",
	[Instrument.FrenchHorn] = "war-horn",
	[Instrument.BrassSection] = "trumpet",
	[Instrument.SynthBrass1] = "trumpet",
	[Instrument.SynthBrass2] = "trumpet",

	-- Reed
	[Instrument.SopranoSax] = "clarinet",
	[Instrument.AltoSax] = "clarinet",
	[Instrument.TenorSax] = "bassoon",
	[Instrument.BaritoneSax] = "bassoon",
	[Instrument.Oboe] = "clarinet",
	[Instrument.EnglishHorn] = "clarinet",
	[Instrument.Bassoon] = "bassoon",
	[Instrument.Clarinet] = "clarinet",

	-- Pipe
	[Instrument.Piccolo] = "recorder",
	[Instrument.Flute] = "recorder",
	[Instrument.Recorder] = "recorder",
	[Instrument.PanFlute] = "recorder",
	[Instrument.BlownBottle] = "recorder",
	[Instrument.Shakuhachi] = "recorder",
	[Instrument.Whistle] = "recorder",
	[Instrument.Ocarina] = "recorder",

	-- Synth Lead
	[Instrument.Lead1Square] = "clarinet",
	[Instrument.Lead2Sawtooth] = "fiddle",
	[Instrument.Lead3Calliope] = "recorder",
	[Instrument.Lead4Chiff] = "recorder",
	[Instrument.Lead5Charang] = "recorder",
	[Instrument.Lead6Voice] = "female-voice",
	[Instrument.Lead7Fifths] = "fiddle",
	[Instrument.Lead8BassLead] = "lute",

	-- Synth Pad
	[Instrument.Pad1Newage] = "lute",
	[Instrument.Pad2Warm] = "fiddle",
	[Instrument.Pad3Polysynth] = "fiddle",
	[Instrument.Pad4Choir] = "fiddle",
	[Instrument.Pad5Bowed] = "fiddle",
	[Instrument.Pad6Metallic] = "fiddle",
	[Instrument.Pad7Halo] = "fiddle",
	[Instrument.Pad8Sweep] = "fiddle",

	-- Synth Effects
	[Instrument.FX1Rain] = "dulcimer",
	[Instrument.FX2Soundtrack] = "dulcimer",
	[Instrument.FX3Crystal] = "dulcimer",
	[Instrument.FX4Atmosphere] = "dulcimer",
	[Instrument.FX5Brightness] = "dulcimer",
	[Instrument.FX6Goblins] = "dulcimer",
	[Instrument.FX7Echoes] = "dulcimer",
	[Instrument.FX8SciFi] = "dulcimer",

	-- Ethnic
	[Instrument.Sitar] = "harp",
	[Instrument.Banjo] = "lute",
	[Instrument.Shamisen] = "lute",
	[Instrument.Koto] = "harp",
	[Instrument.Kalimba] = "dulcimer",
	[Instrument.Bagpipe] = "bagpipe",
	[Instrument.Fiddle] = "fiddle",
	[Instrument.Shanai] = "bagpipe",

	-- Percussive
	[Instrument.TinkleBell] = "lute",
	[Instrument.Agogo] = "none",
	[Instrument.SteelDrums] = "dulcimer",
	[Instrument.Woodblock] = "none",
	[Instrument.TaikoDrum] = "none",
	[Instrument.MelodicTom] = "none",
	[Instrument.SynthDrum] = "none",
	[Instrument.ReverseCymbal] = "none",

	-- Sound Effects
	[Instrument.GuitarFretNoise] = "none",
	[Instrument.BreathNoise] = "none",
	[Instrument.Seashore] = "none",
	[Instrument.BirdTweet] = "none",
	[Instrument.TelephoneRing] = "none",
	[Instrument.Helicopter] = "none",
	[Instrument.Applause] = "none",
	[Instrument.Gunshot] = "none",

	-- Percussions
	[Instrument.Percussions] = "percussions",
	[Instrument.Drumkit] = "drumkit",

	-- None
	[Instrument.None] = "none",
}

Musician.MIDI_PERCUSSION_MAPPING = {
	[Percussion.Laser] = "none",
	[Percussion.Whip] = "none",
	[Percussion.ScratchPush] = "none",
	[Percussion.ScratchPull] = "none",
	[Percussion.StickClick] = "none",
	[Percussion.SquareClick] = "none",
	[Percussion.MetronomeClick] = "none",
	[Percussion.MetronomeBell] = "none",
	[Percussion.AcousticBassDrum] = "none",
	[Percussion.BassDrum1] = "none",
	[Percussion.SideStick] = "none",
	[Percussion.AcousticSnare] = "none",
	[Percussion.HandClap] = "none",
	[Percussion.ElectricSnare] = "none",
	[Percussion.LowFloorTom] = "none",
	[Percussion.ClosedHiHat] = "none",
	[Percussion.HighFloorTom] = "none",
	[Percussion.PedalHiHat] = "none",
	[Percussion.LowTom] = "none",
	[Percussion.OpenHiHat] = "none",
	[Percussion.LowMidTom] = "none",
	[Percussion.HiMidTom] = "none",
	[Percussion.CrashCymbal1] = "none",
	[Percussion.HighTom] = "none",
	[Percussion.RideCymbal1] = "none",
	[Percussion.ChineseCymbal] = "none",
	[Percussion.RideBell] = "none",
	[Percussion.Tambourine] = "none",
	[Percussion.SplashCymbal] = "none",
	[Percussion.Cowbell] = "none",
	[Percussion.CrashCymbal2] = "none",
	[Percussion.Vibraslap] = "none",
	[Percussion.RideCymbal2] = "none",
	[Percussion.HiBongo] = "none",
	[Percussion.LowBongo] = "none",
	[Percussion.MuteHiConga] = "none",
	[Percussion.OpenHiConga] = "none",
	[Percussion.LowConga] = "none",
	[Percussion.HighTimbale] = "none",
	[Percussion.LowTimbale] = "none",
	[Percussion.HighAgogo] = "none",
	[Percussion.LowAgogo] = "none",
	[Percussion.Cabasa] = "none",
	[Percussion.Maracas] = "none",
	[Percussion.ShortWhistle] = "none",
	[Percussion.LongWhistle] = "none",
	[Percussion.ShortGuiro] = "none",
	[Percussion.LongGuiro] = "none",
	[Percussion.Claves] = "none",
	[Percussion.HiWoodBlock] = "none",
	[Percussion.LowWoodBlock] = "none",
	[Percussion.MuteCuica] = "none",
	[Percussion.OpenCuica] = "none",
	[Percussion.MuteTriangle] = "none",
	[Percussion.OpenTriangle] = "none",
	[Percussion.Shaker] = "none",
	[Percussion.SleighBell] = "none",
	[Percussion.BellTree] = "none",
	[Percussion.Castanets] = "none",
	[Percussion.SurduDeadStroke] = "none",
	[Percussion.Surdu] = "none",
	[Percussion.SnareDrumRod] = "none",
	[Percussion.OceanDrum] = "none",
	[Percussion.SnareDrumBrush] = "none",
}
