@ECHO OFF
ECHO Generating .vmssf soundfont list file for CoolSoft VirtualMIDISynth...
ECHO [SoundFonts] > Musician_GM_soundfonts.vmssf
ECHO sf1=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf1.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf1.preset=0 >> Musician_GM_soundfonts.vmssf
ECHO sf1.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf2=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf2.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf2.preset=1 >> Musician_GM_soundfonts.vmssf
ECHO sf2.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf3=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf3.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf3.preset=2 >> Musician_GM_soundfonts.vmssf
ECHO sf3.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf4=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf4.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf4.preset=3 >> Musician_GM_soundfonts.vmssf
ECHO sf4.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf5=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf5.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf5.preset=4 >> Musician_GM_soundfonts.vmssf
ECHO sf5.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf6=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf6.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf6.preset=5 >> Musician_GM_soundfonts.vmssf
ECHO sf6.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf7=%cd%\[000-046] Harp.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf7.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf7.preset=6 >> Musician_GM_soundfonts.vmssf
ECHO sf7.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf8=%cd%\[000-046] Harp.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf8.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf8.preset=7 >> Musician_GM_soundfonts.vmssf
ECHO sf8.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf9=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf9.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf9.preset=8 >> Musician_GM_soundfonts.vmssf
ECHO sf9.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf10=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf10.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf10.preset=9 >> Musician_GM_soundfonts.vmssf
ECHO sf10.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf11=%cd%\[000-046] Harp.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf11.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf11.preset=10 >> Musician_GM_soundfonts.vmssf
ECHO sf11.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf12=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf12.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf12.preset=11 >> Musician_GM_soundfonts.vmssf
ECHO sf12.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf13=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf13.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf13.preset=12 >> Musician_GM_soundfonts.vmssf
ECHO sf13.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf14=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf14.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf14.preset=13 >> Musician_GM_soundfonts.vmssf
ECHO sf14.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf15=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf15.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf15.preset=14 >> Musician_GM_soundfonts.vmssf
ECHO sf15.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf16=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf16.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf16.preset=15 >> Musician_GM_soundfonts.vmssf
ECHO sf16.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf17=%cd%\[000-021] Accordion.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf17.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf17.preset=16 >> Musician_GM_soundfonts.vmssf
ECHO sf17.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf18=%cd%\[000-021] Accordion.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf18.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf18.preset=17 >> Musician_GM_soundfonts.vmssf
ECHO sf18.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf19=%cd%\[000-021] Accordion.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf19.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf19.preset=18 >> Musician_GM_soundfonts.vmssf
ECHO sf19.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf20=%cd%\[000-021] Accordion.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf20.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf20.preset=19 >> Musician_GM_soundfonts.vmssf
ECHO sf20.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf21=%cd%\[000-021] Accordion.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf21.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf21.preset=20 >> Musician_GM_soundfonts.vmssf
ECHO sf21.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf22=%cd%\[000-021] Accordion.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf22.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf22.preset=21 >> Musician_GM_soundfonts.vmssf
ECHO sf22.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf23=%cd%\[000-021] Accordion.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf23.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf23.preset=22 >> Musician_GM_soundfonts.vmssf
ECHO sf23.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf24=%cd%\[000-021] Accordion.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf24.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf24.preset=23 >> Musician_GM_soundfonts.vmssf
ECHO sf24.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf25=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf25.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf25.preset=24 >> Musician_GM_soundfonts.vmssf
ECHO sf25.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf26=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf26.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf26.preset=25 >> Musician_GM_soundfonts.vmssf
ECHO sf26.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf27=%cd%\[000-027] Clean guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf27.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf27.preset=26 >> Musician_GM_soundfonts.vmssf
ECHO sf27.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf28=%cd%\[000-027] Clean guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf28.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf28.preset=27 >> Musician_GM_soundfonts.vmssf
ECHO sf28.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf29=%cd%\[000-027] Clean guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf29.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf29.preset=28 >> Musician_GM_soundfonts.vmssf
ECHO sf29.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf30=%cd%\[000-029] Distorsion guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf30.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf30.preset=29 >> Musician_GM_soundfonts.vmssf
ECHO sf30.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf31=%cd%\[000-029] Distorsion guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf31.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf31.preset=30 >> Musician_GM_soundfonts.vmssf
ECHO sf31.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf32=%cd%\[000-029] Distorsion guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf32.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf32.preset=31 >> Musician_GM_soundfonts.vmssf
ECHO sf32.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf33=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf33.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf33.preset=32 >> Musician_GM_soundfonts.vmssf
ECHO sf33.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf34=%cd%\[000-033] Bass guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf34.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf34.preset=33 >> Musician_GM_soundfonts.vmssf
ECHO sf34.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf35=%cd%\[000-033] Bass guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf35.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf35.preset=34 >> Musician_GM_soundfonts.vmssf
ECHO sf35.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf36=%cd%\[000-033] Bass guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf36.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf36.preset=35 >> Musician_GM_soundfonts.vmssf
ECHO sf36.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf37=%cd%\[000-033] Bass guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf37.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf37.preset=36 >> Musician_GM_soundfonts.vmssf
ECHO sf37.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf38=%cd%\[000-033] Bass guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf38.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf38.preset=37 >> Musician_GM_soundfonts.vmssf
ECHO sf38.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf39=%cd%\[000-033] Bass guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf39.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf39.preset=38 >> Musician_GM_soundfonts.vmssf
ECHO sf39.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf40=%cd%\[000-033] Bass guitar.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf40.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf40.preset=39 >> Musician_GM_soundfonts.vmssf
ECHO sf40.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf41=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf41.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf41.preset=40 >> Musician_GM_soundfonts.vmssf
ECHO sf41.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf42=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf42.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf42.preset=41 >> Musician_GM_soundfonts.vmssf
ECHO sf42.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf43=%cd%\[000-042] Viola da gamba.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf43.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf43.preset=42 >> Musician_GM_soundfonts.vmssf
ECHO sf43.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf44=%cd%\[000-042] Viola da gamba.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf44.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf44.preset=43 >> Musician_GM_soundfonts.vmssf
ECHO sf44.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf45=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf45.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf45.preset=44 >> Musician_GM_soundfonts.vmssf
ECHO sf45.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf46=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf46.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf46.preset=45 >> Musician_GM_soundfonts.vmssf
ECHO sf46.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf47=%cd%\[000-046] Harp.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf47.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf47.preset=46 >> Musician_GM_soundfonts.vmssf
ECHO sf47.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf48=%cd%\[000-047] War drum.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf48.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf48.preset=47 >> Musician_GM_soundfonts.vmssf
ECHO sf48.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf49=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf49.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf49.preset=48 >> Musician_GM_soundfonts.vmssf
ECHO sf49.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf50=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf50.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf50.preset=49 >> Musician_GM_soundfonts.vmssf
ECHO sf50.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf51=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf51.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf51.preset=50 >> Musician_GM_soundfonts.vmssf
ECHO sf51.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf52=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf52.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf52.preset=51 >> Musician_GM_soundfonts.vmssf
ECHO sf52.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf53=%cd%\[000-052] Male voice.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf53.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf53.preset=52 >> Musician_GM_soundfonts.vmssf
ECHO sf53.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf54=%cd%\[000-053] Female voice.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf54.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf54.preset=53 >> Musician_GM_soundfonts.vmssf
ECHO sf54.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf55=%cd%\[000-053] Female voice.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf55.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf55.preset=54 >> Musician_GM_soundfonts.vmssf
ECHO sf55.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf56=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf56.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf56.preset=55 >> Musician_GM_soundfonts.vmssf
ECHO sf56.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf57=%cd%\[000-056] Trumpet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf57.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf57.preset=56 >> Musician_GM_soundfonts.vmssf
ECHO sf57.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf58=%cd%\[000-057] Sackbut.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf58.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf58.preset=57 >> Musician_GM_soundfonts.vmssf
ECHO sf58.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf59=%cd%\[000-060] War horn.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf59.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf59.preset=58 >> Musician_GM_soundfonts.vmssf
ECHO sf59.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf60=%cd%\[000-056] Trumpet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf60.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf60.preset=59 >> Musician_GM_soundfonts.vmssf
ECHO sf60.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf61=%cd%\[000-060] War horn.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf61.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf61.preset=60 >> Musician_GM_soundfonts.vmssf
ECHO sf61.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf62=%cd%\[000-056] Trumpet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf62.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf62.preset=61 >> Musician_GM_soundfonts.vmssf
ECHO sf62.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf63=%cd%\[000-056] Trumpet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf63.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf63.preset=62 >> Musician_GM_soundfonts.vmssf
ECHO sf63.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf64=%cd%\[000-056] Trumpet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf64.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf64.preset=63 >> Musician_GM_soundfonts.vmssf
ECHO sf64.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf65=%cd%\[000-071] Clarinet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf65.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf65.preset=64 >> Musician_GM_soundfonts.vmssf
ECHO sf65.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf66=%cd%\[000-071] Clarinet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf66.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf66.preset=65 >> Musician_GM_soundfonts.vmssf
ECHO sf66.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf67=%cd%\[000-070] Bassoon.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf67.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf67.preset=66 >> Musician_GM_soundfonts.vmssf
ECHO sf67.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf68=%cd%\[000-070] Bassoon.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf68.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf68.preset=67 >> Musician_GM_soundfonts.vmssf
ECHO sf68.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf69=%cd%\[000-071] Clarinet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf69.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf69.preset=68 >> Musician_GM_soundfonts.vmssf
ECHO sf69.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf70=%cd%\[000-071] Clarinet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf70.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf70.preset=69 >> Musician_GM_soundfonts.vmssf
ECHO sf70.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf71=%cd%\[000-070] Bassoon.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf71.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf71.preset=70 >> Musician_GM_soundfonts.vmssf
ECHO sf71.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf72=%cd%\[000-071] Clarinet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf72.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf72.preset=71 >> Musician_GM_soundfonts.vmssf
ECHO sf72.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf73=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf73.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf73.preset=72 >> Musician_GM_soundfonts.vmssf
ECHO sf73.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf74=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf74.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf74.preset=73 >> Musician_GM_soundfonts.vmssf
ECHO sf74.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf75=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf75.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf75.preset=74 >> Musician_GM_soundfonts.vmssf
ECHO sf75.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf76=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf76.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf76.preset=75 >> Musician_GM_soundfonts.vmssf
ECHO sf76.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf77=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf77.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf77.preset=76 >> Musician_GM_soundfonts.vmssf
ECHO sf77.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf78=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf78.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf78.preset=77 >> Musician_GM_soundfonts.vmssf
ECHO sf78.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf79=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf79.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf79.preset=78 >> Musician_GM_soundfonts.vmssf
ECHO sf79.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf80=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf80.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf80.preset=79 >> Musician_GM_soundfonts.vmssf
ECHO sf80.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf81=%cd%\[000-071] Clarinet.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf81.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf81.preset=80 >> Musician_GM_soundfonts.vmssf
ECHO sf81.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf82=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf82.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf82.preset=81 >> Musician_GM_soundfonts.vmssf
ECHO sf82.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf83=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf83.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf83.preset=82 >> Musician_GM_soundfonts.vmssf
ECHO sf83.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf84=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf84.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf84.preset=83 >> Musician_GM_soundfonts.vmssf
ECHO sf84.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf85=%cd%\[000-074] Recorder.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf85.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf85.preset=84 >> Musician_GM_soundfonts.vmssf
ECHO sf85.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf86=%cd%\[000-053] Female voice.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf86.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf86.preset=85 >> Musician_GM_soundfonts.vmssf
ECHO sf86.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf87=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf87.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf87.preset=86 >> Musician_GM_soundfonts.vmssf
ECHO sf87.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf88=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf88.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf88.preset=87 >> Musician_GM_soundfonts.vmssf
ECHO sf88.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf89=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf89.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf89.preset=88 >> Musician_GM_soundfonts.vmssf
ECHO sf89.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf90=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf90.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf90.preset=89 >> Musician_GM_soundfonts.vmssf
ECHO sf90.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf91=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf91.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf91.preset=90 >> Musician_GM_soundfonts.vmssf
ECHO sf91.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf92=%cd%\[000-053] Female voice.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf92.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf92.preset=91 >> Musician_GM_soundfonts.vmssf
ECHO sf92.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf93=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf93.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf93.preset=92 >> Musician_GM_soundfonts.vmssf
ECHO sf93.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf94=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf94.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf94.preset=93 >> Musician_GM_soundfonts.vmssf
ECHO sf94.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf95=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf95.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf95.preset=94 >> Musician_GM_soundfonts.vmssf
ECHO sf95.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf96=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf96.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf96.preset=95 >> Musician_GM_soundfonts.vmssf
ECHO sf96.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf97=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf97.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf97.preset=96 >> Musician_GM_soundfonts.vmssf
ECHO sf97.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf98=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf98.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf98.preset=97 >> Musician_GM_soundfonts.vmssf
ECHO sf98.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf99=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf99.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf99.preset=98 >> Musician_GM_soundfonts.vmssf
ECHO sf99.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf100=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf100.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf100.preset=99 >> Musician_GM_soundfonts.vmssf
ECHO sf100.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf101=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf101.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf101.preset=100 >> Musician_GM_soundfonts.vmssf
ECHO sf101.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf102=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf102.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf102.preset=101 >> Musician_GM_soundfonts.vmssf
ECHO sf102.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf103=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf103.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf103.preset=102 >> Musician_GM_soundfonts.vmssf
ECHO sf103.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf104=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf104.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf104.preset=103 >> Musician_GM_soundfonts.vmssf
ECHO sf104.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf105=%cd%\[000-046] Harp.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf105.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf105.preset=104 >> Musician_GM_soundfonts.vmssf
ECHO sf105.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf106=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf106.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf106.preset=105 >> Musician_GM_soundfonts.vmssf
ECHO sf106.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf107=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf107.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf107.preset=106 >> Musician_GM_soundfonts.vmssf
ECHO sf107.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf108=%cd%\[000-046] Harp.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf108.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf108.preset=107 >> Musician_GM_soundfonts.vmssf
ECHO sf108.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf109=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf109.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf109.preset=108 >> Musician_GM_soundfonts.vmssf
ECHO sf109.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf110=%cd%\[000-109] Bagpipe.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf110.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf110.preset=109 >> Musician_GM_soundfonts.vmssf
ECHO sf110.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf111=%cd%\[000-110] Fiddle.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf111.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf111.preset=110 >> Musician_GM_soundfonts.vmssf
ECHO sf111.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf112=%cd%\[000-109] Bagpipe.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf112.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf112.preset=111 >> Musician_GM_soundfonts.vmssf
ECHO sf112.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf113=%cd%\[000-024] Lute.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf113.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf113.preset=112 >> Musician_GM_soundfonts.vmssf
ECHO sf113.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf114=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf114.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf114.preset=113 >> Musician_GM_soundfonts.vmssf
ECHO sf114.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf115=%cd%\[000-015] Dulcimer.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf115.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf115.preset=114 >> Musician_GM_soundfonts.vmssf
ECHO sf115.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf116=%cd%\[000-115] Woodblock.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf116.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf116.preset=115 >> Musician_GM_soundfonts.vmssf
ECHO sf116.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf117=%cd%\[000-047] War drum.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf117.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf117.preset=116 >> Musician_GM_soundfonts.vmssf
ECHO sf117.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf118=%cd%\[000-047] War drum.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf118.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf118.preset=117 >> Musician_GM_soundfonts.vmssf
ECHO sf118.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf119=%cd%\[000-047] War drum.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf119.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf119.preset=118 >> Musician_GM_soundfonts.vmssf
ECHO sf119.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf120=%cd%\[000-119] Tambourine shake.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf120.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf120.preset=119 >> Musician_GM_soundfonts.vmssf
ECHO sf120.bank=0 >> Musician_GM_soundfonts.vmssf
ECHO sf121=%cd%\[128-000] Percussions.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf121.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf121.preset=0 >> Musician_GM_soundfonts.vmssf
ECHO sf121.bank=128 >> Musician_GM_soundfonts.vmssf
ECHO sf122=%cd%\[128-000] Percussions.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf122.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf122.preset=8 >> Musician_GM_soundfonts.vmssf
ECHO sf122.bank=128 >> Musician_GM_soundfonts.vmssf
ECHO sf123=%cd%\[128-016] Drumkit.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf123.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf123.preset=16 >> Musician_GM_soundfonts.vmssf
ECHO sf123.bank=128 >> Musician_GM_soundfonts.vmssf
ECHO sf124=%cd%\[128-016] Drumkit.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf124.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf124.preset=24 >> Musician_GM_soundfonts.vmssf
ECHO sf124.bank=128 >> Musician_GM_soundfonts.vmssf
ECHO sf125=%cd%\[128-016] Drumkit.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf125.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf125.preset=25 >> Musician_GM_soundfonts.vmssf
ECHO sf125.bank=128 >> Musician_GM_soundfonts.vmssf
ECHO sf126=%cd%\[128-000] Percussions.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf126.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf126.preset=32 >> Musician_GM_soundfonts.vmssf
ECHO sf126.bank=128 >> Musician_GM_soundfonts.vmssf
ECHO sf127=%cd%\[128-000] Percussions.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf127.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf127.preset=40 >> Musician_GM_soundfonts.vmssf
ECHO sf127.bank=128 >> Musician_GM_soundfonts.vmssf
ECHO sf128=%cd%\[128-000] Percussions.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf128.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf128.preset=48 >> Musician_GM_soundfonts.vmssf
ECHO sf128.bank=128 >> Musician_GM_soundfonts.vmssf
ECHO sf129=%cd%\[128-000] Percussions.sfz >> Musician_GM_soundfonts.vmssf
ECHO sf129.enabled=1 >> Musician_GM_soundfonts.vmssf
ECHO sf129.preset=127 >> Musician_GM_soundfonts.vmssf
ECHO sf129.bank=128 >> Musician_GM_soundfonts.vmssf
ECHO Done
PAUSE
